### ISSUE TITLE
Inappropriate use of `sleep` dataset in vignette examples

### ISSUE THREAD

**Issue by jhmaindonald** [easystats/bayestestR#527] opened 2022-05-07 00:13 UTC
I do not understand why examples in the [the Bayes factors vignette](https://easystats.github.io/bayestestR/articles/bayes_factors.html)  treat the `datatsets::sleep` data as two-sample (unpaired).  The help page `?sleep' makes it clear that the data are paired, with examples that give two versions of the frequentist paired t-test that take account of the pairing. It is surely important to reflect good statistical practice as well as demonstrate methodology.  Unless, of course, the aim is to show just what one should not be doing!

I notice that the same inappropriate use of the data appears in the vignettes [fbst::fbet](http://127.0.0.1:23521/help/library/fbst/doc/fbet.html) and
[fbst::fbst](http://127.0.0.1:23521/help/library/fbst/doc/fbst.html) for the `fbst` package.

**Comment by mattansb** [comment] 2022-05-07 05:35
Duplicate of #466

**Closed** 2022-05-07 05:35 UTC

**Comment by jhmaindonald** [comment] 2022-05-07 05:55
OK, I did have a vague idea that I might have raised this earlier, but could not locate the issue number.
I do have a strong view about this — there will be some users  who will be misled and/or puzzled
because the Bayes Factor is so small relative to the p-value in a case with modest sample size. I am
not proposing a specific fix because there is an issue, highlighted by the comment that it might be
more appropriate to fit a full model.  This is a concern because I propose to highlight the comparison
with BayesFactor in the text for which we are currently completing a draft, but if the examples stay as
they are will include a warning. 

By comparison with Bayesfactor, I’ve not found itm easy to get on top of what bayestestR is doing.
I am at a stage of life where my mental capacities are not what they were in my prime, but still well
ahead of most people in application areas who may use these methods.
 
John Maindonald.
