### ISSUE TITLE
Check warnings for vignette

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#161] opened 2019-06-03 09:15 UTC
https://cran.r-project.org/web/checks/check_results_bayestestR.html

**Comment by DominiqueMakowski** [comment] 2019-06-03 09:46
It is most likely caused by the fact that the vignette and the corresponding data changed. It will be solved in the next version with the updated vignettes

**Comment by strengejacke** [comment] 2019-06-05 09:48
Maybe related to #164, so we have two reasons for an "in-between" update on CRAN.

**Comment by DominiqueMakowski** [comment] 2019-06-10 08:39
```
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_bayestestR.html>.

Please correct before 2019-06-23 to safely retain your package on CRAN.

Best,
```

Which means we can safely ship an update soon.

**Comment by strengejacke** [comment] 2019-06-10 08:59
Ok, which version number do we want? 0.2.x or 0.3.0? Are the vignette-issues fixed?

**Comment by mattansb** [comment] 2019-06-10 09:04
I suggest 0.2.x - we have only a few user-facing changes in this update.

**Comment by strengejacke** [comment] 2019-06-10 09:16
Do you want to address https://github.com/easystats/bayestestR/issues/168? Either by closing or revising, or later for >= 0.3.0?

**Comment by DominiqueMakowski** [comment] 2019-06-10 09:30
> Do you want to address #168? 

I think we can close it, I've reread the documentation and it is stated very clearly everywhere that it is a percentage and not a proportion. I've also added information about the return type. But I am quite confident about this one to keep it as is :)

> Ok, which version number do we want? 0.2.x or 0.3.0?

0.2.x sounds good.

**Comment by strengejacke** [comment] 2019-06-10 09:41
> But I am quite confident about this one to keep it as is :)

Ok, but don't say I haven't warned you! ;-) 

(I still think it's confusing, since it's not self-explanatory that "100" actually means "1", because there is no percentage sign in the return value...)

**Comment by strengejacke** [comment] 2019-06-10 09:44
Just to give another example:
https://en.wikipedia.org/wiki/Coefficient_of_determination#As_explained_variance

.49 is **49%** (and 49 is _not_ 49%)

**Comment by strengejacke** [comment] 2019-06-10 15:06
Might be of interest:
https://www.r-bloggers.com/overview-of-the-cran-checks-api/

**Comment by DominiqueMakowski** [comment] 2019-06-20 04:48
Dear maintainer,

package bayestestR_0.2.2.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/bayestestR_0.2.2_20190620_032821/Windows/00check.log>
Status: 1 ERROR, 1 WARNING
Debian: <https://win-builder.r-project.org/incoming_pretest/bayestestR_0.2.2_20190620_032821/Debian/00check.log>
Status: 1 ERROR, 1 WARNING

**Comment by mattansb** [comment] 2019-06-20 04:52
(Also errors in the emmGrid test?? What the F? Maybe lower the tolerance on that test?)

**Comment by strengejacke** [comment] 2019-06-20 08:35
For me, locally all tests run fine and also the vignette compiles w/o error...

**Comment by strengejacke** [comment] 2019-06-20 08:39
I just uploaded the source tarball from the current dev-branch to win-builder, could you share the results when they come in? (in ~ 1hour).

**Comment by DominiqueMakowski** [comment] 2019-06-20 09:14
Dear package maintainer,

this notification has been generated automatically.
Your package bayestestR_0.2.2.tar.gz has been built (if working) and checked for Windows.
Please check the log files and (if working) the binary package at:
https://win-builder.r-project.org/5l6Nus7zrJPt
The files will be removed after roughly 72 hours.
Installation time in seconds: 7
Check time in seconds: 314
Status: 2 ERRORs, 2 WARNINGs


https://win-builder.r-project.org/U42Y89ouMKfv

https://win-builder.r-project.org/m46WH70AG6cd

**Comment by DominiqueMakowski** [comment] 2019-06-20 09:32
For emmgrid it seems not to be a matter of tolerance as the difference seems huge! Either we deactivated these tests on CRAN to submit fast, or we try to fix it but I am not sure how as I cannot reproduce either :/

**Comment by DominiqueMakowski** [comment] 2019-06-20 09:32
It seems that only the BF is affected

**Comment by strengejacke** [comment] 2019-06-20 09:37
I just installed the latest dev-build (R 3.7), which meant that I also needed to re-install *all* packages. Just running checks, but it seems I can't reproduce the errors here, too.

It's curious that the differences in the tests are such large, and it's strange why the example2-vignettes fails to build (due to lines 71-73). I can't find anything suspicious there.

**Comment by strengejacke** [comment] 2019-06-20 09:38
Let's deactivate the tests for now, and send to winbuilder again. We must check that the vignette (example2 in particula) is OK.

**Comment by mattansb** [comment] 2019-06-20 09:41
Yes... I added `testthat::skip_on_cran()` to where the emmGrid-BF is tested. (Note this is exactly the same error we got on Travis - maybe something to do with how their machines deal with `set.seed`? I've read some issues on this since 3.6.0). Anyway, differences aren't that huge - they are within the expected range considering the re-sampling of priors and the estimation of density etc...

**Comment by strengejacke** [comment] 2019-06-20 09:47
I'll commit some fixed to the vignettes, that should reduce the warnings, stay tuned.

**Comment by strengejacke** [comment] 2019-06-20 09:54
Ok, the **very long** list of warnings for the one vignette should be fixed now. @DominiqueMakowski can you send to winbuilder again once you think everything is done from your side?

**Comment by DominiqueMakowski** [comment] 2019-06-20 09:59
I am in the subway could you please send it if you can, otherwise I'll send in 1h, thanks!

**Comment by strengejacke** [comment] 2019-06-20 10:00
Yes, no problem, so there are no current changes from you anyway, when you're travelling ;-)

**Comment by DominiqueMakowski** [comment] 2019-06-20 10:18
https://win-builder.r-project.org/e6UEnM8MKPzx

**Comment by strengejacke** [comment] 2019-06-20 10:22
That was the old msg from the third check of the previous winbuilder-submission, right? New results should come in the next 20-40 minutes.

**Comment by DominiqueMakowski** [comment] 2019-06-20 10:34
https://win-builder.r-project.org/13BP7U16X8Rq

**Comment by strengejacke** [comment] 2019-06-20 11:14
Looks like the only issue left is:

> --- re-building 'example2.Rmd' using rmarkdown
Quitting from lines 72-73 (example2.Rmd) 
Error: processing vignette 'example2.Rmd' failed with diagnostics:
arguments imply differing number of rows: 0, 1
--- failed re-building 'example2.Rmd'

But I don't know why the vignette fails at those lines...

**Comment by strengejacke** [comment] 2019-06-20 11:21
ok, next try... I'll submit to winbuilder again (even if previous checks were not completely done).

**Comment by DominiqueMakowski** [comment] 2019-06-20 11:37
https://win-builder.r-project.org/mZBuRvq9uzE3 emmgrid again 😱

**Comment by DominiqueMakowski** [comment] 2019-06-20 11:39
https://win-builder.r-project.org/SLXnO1q72lHU 🎉 (I think the "warning" related to the logo is a false alarm?)

**Comment by DominiqueMakowski** [comment] 2019-06-20 11:49
https://win-builder.r-project.org/VV0G0dnUBr1l 🎉

**Comment by strengejacke** [comment] 2019-06-20 12:03
Yes, that's a false positive I would say.

**Comment by DominiqueMakowski** [comment] 2019-06-20 12:04
Thanks, should I try resubmitting to CRAN?

**Comment by strengejacke** [comment] 2019-06-20 12:09
Are emmgrid tests skipped / deactivated on CRAN? I think so... If yes, try to resubmit.

**Closed** 2019-06-21 09:56 UTC
