### ISSUE TITLE
check for collinearity of covariates when computing ROPE + HDI

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#71] opened 2019-04-16 06:56 UTC
See email.

**Comment by DominiqueMakowski** [comment] 2019-04-21 12:28
As the collinearity issue seems to be quite transversal to frequentist and Bayesian models, maybe a function to detect/warn/deal (`check_collinearity`) with collinearity between parameters would be more relevant in parameters?

Some resources on collinearity detection:

- https://stats.stackexchange.com/questions/82984/how-to-test-and-avoid-multicollinearity-in-mixed-linear-model
- https://cran.r-project.org/web/packages/olsrr/vignettes/regression_diagnostics.html

**Comment by DominiqueMakowski** [comment] 2019-05-12 03:06
Closing this as this will more likely be dealt with in other places (performance)

**Closed by DominiqueMakowski** 2019-05-12 03:06 UTC

**Comment by strengejacke** [comment] 2019-05-12 05:18
We have a check method, see at the end of here
https://github.com/easystats/bayestestR/blob/master/R/equivalence_test.R
I use it for equivalence test, we could also use it for rope.

**Comment by DominiqueMakowski** [comment] 2019-05-12 05:21
I wonder though to what extent is this check specific to any index. I feel like this a general issue that alters the parameters *in general*, and thus all indices that we can derive from these parameters.

**Comment by strengejacke** [comment] 2019-05-12 05:24
I think the rope is sensitive against correlation of parameters, and thus HDI. There is also a small paragraph in Kruschke 2015 on this topic.
