### ISSUE TITLE
Fix issues [26/07]

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#444] opened 2021-07-12 05:53 UTC
```
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_bayestestR.html>.

Please correct before 2021-07-26 to safely retain your package on CRAN.

The CRAN Team
```

The problem is I literally cannot build bayestestR :/

**Comment by mattansb** [comment] 2021-07-13 05:15
Me neither... I'm getting:

```
Error in dirname(file) : a character vector argument expected
Calls: suppressPackageStartupMessages ... tweak_links -> get_rd_from_help -> <Anonymous> -> dirname
```

**Comment by DominiqueMakowski** [comment] 2021-07-13 05:37
Same as me then 😱

**Comment by strengejacke** [comment] 2021-07-15 22:11
Should be fixed with https://github.com/easystats/bayestestR/commit/afe5ddc21f45e0fbbeadc9767c99dbfa027a0528

**Comment by IndrajeetPatil** [comment] 2021-07-16 15:37
The issue seems to be this, no?

```r
== Failed tests ================================================================
     -- Error (test-blavaan.R:79:5): blavaan, all -----------------------------------
```

**Comment by strengejacke** [comment] 2021-07-16 16:00
Yes, I was referring to the installation issue. The package should install now

**Comment by mattansb** [comment] 2021-07-18 05:02
The blavaan tests seem to be running fine on my machine... What are you getting?

**Comment by IndrajeetPatil** [comment] 2021-07-18 05:17
I am not sure if we are going to be able to reproduce this behavior without special setup since some tests are failing only on ATLAS platform:
https://www.stats.ox.ac.uk/pub/bdr/Rblas/ATLAS/bayestestR.out

If it's of any help, this is the traceback:

```r
── Error (test-blavaan.R:79:5): blavaan, all ───────────────────────────────────
  Error: replacement has length zero
  Backtrace:
       █
    1. ├─bayestestR::unupdate(bfit) test-blavaan.R:79:4
    2. └─bayestestR:::unupdate.blavaan(bfit)
    3.   ├─base::suppressMessages(suppressWarnings(utils::capture.output(model_prior <- eval(cl))))
    4.   │ └─base::withCallingHandlers(...)
    5.   ├─base::suppressWarnings(utils::capture.output(model_prior <- eval(cl)))
    6.   │ └─base::withCallingHandlers(...)
    7.   ├─utils::capture.output(model_prior <- eval(cl))
    8.   │ └─base::withVisible(...elt(i))
    9.   ├─base::eval(cl)
   10.   │ └─base::eval(cl)
   11.   └─blavaan::blavaan(...)
   12.     └─blavaan:::coeffun_stanmarg(...)
  ```

**Comment by mattansb** [comment] 2021-07-18 05:32
Yeah, def no clue what that is...

**Comment by mattansb** [comment] 2021-07-18 05:33
Added skip on cran...

**Comment by strengejacke** [comment] 2021-07-18 08:11
If you update to the latest blavaan package, you should be able to reproduce the issue.

**Comment by strengejacke** [comment] 2021-07-18 08:32
The issue is in `bayestestR::unupdate.blavaan()`, see following reprex with code-snippets from unupdate.blavaan():

``` r
library(blavaan)
data("PoliticalDemocracy", package = "lavaan")

model <- "
    # latent variable definitions
    dem60 =~ y1 + a*y2
    dem65 =~ y5 + a*y6

    # regressions
    dem65 ~ dem60

    # residual correlations
    y1 ~~ y5
  "

suppressWarnings(capture.output({
  bfit <- blavaan::bsem(model,
                        data = PoliticalDemocracy,
                        n.chains = 1, burnin = 50, sample = 100
  )
}))

cl <- model@call
#> Error in eval(expr, envir, enclos): trying to get slot "call" from an object of a basic class ("character") with no slots
cl$prisamp <- TRUE
#> Error in cl$prisamp <- TRUE: object 'cl' not found
eval(cl)
#> Error in eval(cl): object 'cl' not found
```

<sup>Created on 2021-07-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment] 2021-07-18 08:34
The ATLAS-issue _might_ be a temporary GitHub issue:

> Error: Timeout was reached: [raw.github.com] Resolving timed out after 10000 milliseconds
>   Backtrace:
>       █
>    1. └─insight::download_model("stanreg_merMod_5") test-map_estimate.R:17:4

**Comment by strengejacke** [comment] 2021-07-18 08:38
(sorry, reprex was wrong, edited my post)

**Comment by mattansb** [comment] 2021-07-18 09:48
Very weird.........

@strengejacke I can't seem to get the new version working at all. Can you post this on the `blavaan` forum? https://groups.google.com/g/blavaan

In the meanwhile, I will disable those tests.

**Comment by mattansb** [comment] 2021-07-18 09:51
(Isn't it weird that rev-deps didn't catch this when `blavaan` was updated?)

**Comment by strengejacke** [comment] 2021-07-18 19:58
> (Isn't it weird that rev-deps didn't catch this when blavaan was updated?)

revdep usually doesn't check suggested packages.

**Comment by strengejacke** [comment] 2021-07-18 19:59
> Can you post this on the blavaan forum?

I'm not sure what I should actually post? I don't fully understand the error, because I'm not sure what `unupdate()` is supposed to do, and what recent changes in blavaan now no longer work...?

**Comment by mattansb** [comment] 2021-07-19 05:20
Okay, I've emailed the maintainer directly.

**Comment by mattansb** [comment] 2021-07-19 14:26
Ed Merkle (maintainer of `blavaan`):

> Thanks for the report. I will soon add support for ordinal variables in blavaan, and I broke some things while preparing for that.
I plan to submit a new version of blavaan to CRAN today or tomorrow, and I will make sure that the prior sampling works (and will also add these things to the unit tests...)

So all we need to do is wait a few days (or keep those tests commented if we're in a hurry)

**Comment by IndrajeetPatil** [comment] 2021-07-22 05:37
When are we submitting revised version? We have only 4 days left to getting archived.

**Comment by mattansb** [comment] 2021-07-22 05:55
I think we can go ahead and submit (and re-add the blavaan tests later)

**Comment by strengejacke** [comment] 2021-07-22 06:30
@DominiqueMakowski ?

**Comment by DominiqueMakowski** [comment] 2021-07-23 12:59
submitted

**Closed** 2021-07-29 09:44 UTC
