### ISSUE TITLE
`weighted_posteriors` error for `BFBayesFactor` object

### ISSUE THREAD

**Issue by nahorp** [easystats/bayestestR#345] opened 2020-10-13 02:48 UTC
Hello,

I am running `weighted_posteriors` for a `BFBayesFactor` object but I get the following error,

`Error in make.names(vnames, unique = TRUE) : invalid multibyte string 2`

**Comment by mattansb** [comment] 2020-10-13 06:00
Do you have a reproducible example?

**Comment by nahorp** [comment] 2020-10-13 12:21
Reprex below,

```
# Loading packages

library(tidyverse)
library(BayesFactor)
library(bayestestR)

# Setup data frame

df <- tibble(
  id = factor(rep(1:48, each = 4)),
  g = factor(rep(c("g1","g2","g3"), times = 16, each = 4)),
  s = factor(rep(c("s1","s2"), times = 48, each = 2)),
  b = factor(rep(c("b1","b2"), times = 96, each = 1)),
  y = rnorm(192,5,1) # Nonsensical for the current purposes
)

# Running Bayesian ANOVA

bf <- anovaBF(y ~ g*s*b + id,
              whichRandom = "id",
              data = df)   # disregard high numerical error, not recomputing here

# Weighted posteriors

wp <- weighted_posteriors(bf)
```
My `sessionInfo` below,

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] bayestestR_0.7.2       forcats_0.5.0          stringr_1.4.0         
 [4] dplyr_1.0.2            purrr_0.3.4            readr_1.4.0           
 [7] tidyr_1.1.2            tibble_3.0.4           ggplot2_3.3.2         
[10] tidyverse_1.3.0        BayesFactor_0.9.12-4.2 Matrix_1.2-18         
[13] coda_0.19-4           

loaded via a namespace (and not attached):
  [1] TH.data_1.0-10       colorspace_1.4-1     ellipsis_0.3.1       ggridges_0.5.2      
  [5] brms_2.14.0          rsconnect_0.8.16     estimability_1.3     markdown_1.1        
  [9] fs_1.5.0             base64enc_0.1-3      rstudioapi_0.11      rstan_2.21.3        
 [13] MatrixModels_0.4-1   DT_0.15              fansi_0.4.1          mvtnorm_1.1-1       
 [17] lubridate_1.7.9      xml2_1.3.2           bridgesampling_1.0-0 codetools_0.2-16    
 [21] splines_4.0.2        shinythemes_1.1.2    bayesplot_1.7.2      jsonlite_1.7.1      
 [25] packrat_0.5.0        broom_0.7.1          dbplyr_1.4.4         shiny_1.5.0         
 [29] httr_1.4.2           compiler_4.0.2       emmeans_1.5.1        backports_1.1.10    
 [33] assertthat_0.2.1     fastmap_1.0.1        cli_2.1.0            later_1.1.0.1       
 [37] htmltools_0.5.0      prettyunits_1.1.1    tools_4.0.2          igraph_1.2.6        
 [41] gtable_0.3.0         glue_1.4.2           reshape2_1.4.4       V8_3.2.0            
 [45] Rcpp_1.0.5.1         cellranger_1.1.0     vctrs_0.3.4          nlme_3.1-149        
 [49] crosstalk_1.1.0.1    insight_0.9.6        ps_1.4.0             rvest_0.3.6         
 [53] mime_0.9             miniUI_0.1.1.1       lifecycle_0.2.0      gtools_3.8.2        
 [57] MASS_7.3-53          zoo_1.8-8            scales_1.1.1         colourpicker_1.1.0  
 [61] hms_0.5.3            promises_1.1.1       Brobdingnag_1.2-6    parallel_4.0.2      
 [65] sandwich_3.0-0       inline_0.3.16        shinystan_2.5.0      curl_4.3            
 [69] pbapply_1.4-3        gridExtra_2.3        loo_2.3.1            StanHeaders_2.21.0-6
 [73] stringi_1.5.3        dygraphs_1.1.1.6     pkgbuild_1.1.0       rlang_0.4.8         
 [77] pkgconfig_2.0.3      matrixStats_0.57.0   lattice_0.20-41      rstantools_2.1.1    
 [81] htmlwidgets_1.5.2    processx_3.4.4       tidyselect_1.1.0     plyr_1.8.6          
 [85] magrittr_1.5         R6_2.4.1             generics_0.0.2       multcomp_1.4-14     
 [89] DBI_1.1.0            pillar_1.4.6         haven_2.3.1          withr_2.3.0         
 [93] xts_0.12.1           survival_3.2-7       abind_1.4-5          modelr_0.1.8        
 [97] crayon_1.3.4         bfrms_0.1-0          readxl_1.3.1         grid_4.0.2          
[101] blob_1.2.1           callr_3.5.0          threejs_0.3.3        reprex_0.3.0        
[105] digest_0.6.25        xtable_1.8-4         httpuv_1.5.4         RcppParallel_5.0.2  
[109] stats4_4.0.2         munsell_0.5.0        shinyjs_2.0.0   
```

**Comment by mattansb** [comment] 2020-10-13 12:29
Works on my system..

@DominiqueMakowski @strengejacke can you guys try and run this example?

**Comment by strengejacke** [comment] 2020-10-13 13:15
Not sure what the expected output would be (I got a data frame with 3998 rows and 141 columns), but no error/warning for me.

**Comment by strengejacke** [comment] 2020-10-13 13:16
@nahorp Could you please include the error, and if possible a traceback in your reprex?

**Comment by mattansb** [comment] 2020-10-13 13:36
> Not sure what the expected output would be (I got a data frame with 3998 rows and 141 columns), but no error/warning for me.

Yes, that is the expected output.

**Comment by DominiqueMakowski** [comment] 2020-10-13 13:42
works for me too. Interestingly I have 3999 rows though....

**Comment by mattansb** [comment] 2020-10-13 13:55
differences in number of rows are due to rounding errors (each model is represented by `round(posterior_prob * 4000)`)  + instability of the BFs - set.seed should give you both the same nrows, and in any case it should be very very close to 4000.

**Comment by nahorp** [comment] 2020-10-13 19:08
> @nahorp Could you please include the error, and if possible a traceback in your reprex?

Error and traceback as below,

```
> # Loading packages
> 
> library(tidyverse)
> library(BayesFactor)
> library(bayestestR)
> 
> # Setup data frame
> 
> df <- tibble(
+   id = factor(rep(1:48, each = 4)),
+   g = factor(rep(c("g1","g2","g3"), times = 16, each = 4)),
+   s = factor(rep(c("s1","s2"), times = 48, each = 2)),
+   b = factor(rep(c("b1","b2"), times = 96, each = 1)),
+   y = rnorm(192,5,1) # Nonsensical for the current purposes
+ )
> 
> # Running Bayesian ANOVA
> 
> bf <- anovaBF(y ~ g*s*b + id,
+               whichRandom = "id",
+               data = df)   # disregard high numerical error, not recomputing here
  |=========================================================================================| 100%
Warning message:
data coerced from tibble to data frame 
> 
> # Weighted posteriors
> 
> wp <- weighted_posteriors(bf)
Error in make.names(vnames, unique = TRUE) : invalid multibyte string 11
> traceback()
5: make.names(vnames, unique = TRUE)
4: FUN(X[[i]], ...)
3: lapply(params, data.frame)
2: weighted_posteriors.BFBayesFactor(bf)
1: weighted_posteriors(bf)
>
```

**Comment by strengejacke** [comment] 2020-10-13 20:26
Could this be an OS X issue?

**Comment by strengejacke** [comment] 2020-10-13 20:27
What if you use `data.frame()` instead of `tibble()` to create the data?

**Comment by nahorp** [comment] 2020-10-13 20:31
> What if you use `data.frame()` instead of `tibble()` to create the data?

Did the below and it still gives the same error and traceback too...

```
> df <- as.data.frame(df)
> is.data.frame(df)
[1] TRUE
```

**Comment by strengejacke** [comment] 2020-10-13 21:07
Even `as.data.frame()` on a tibble may keep certain attributes, so you could give it a try with directly using data frame.

**Comment by nahorp** [comment] 2020-10-13 21:11
Still returns the same error when using `data.frame(` instead of `tibble(`...

**Comment by strengejacke** [comment] 2020-10-13 21:11
I had some occasions where tibbles did not behave like  a data frame, and this was really difficult to figure out.

**Comment by strengejacke** [comment] 2020-10-13 21:14
> Still returns the same error when using `data.frame(` instead of `tibble(`...

Ok. Would be great to have someone with OS X for testing.

**Comment by nahorp** [comment] 2020-10-15 05:40
FYI, I've just tried this on a CentOS Linux (virtual computer) and it returns the same error...

**Comment by strengejacke** [comment] 2020-10-15 05:59
@mattansb in `weighted_posteriors.BFBayesFactor()`, the code in line 206:

```r
params[[m]] <- BayesFactor::posterior(1 / Mods[1], iterations = iterations, progress = FALSE)
```

which is used for the first BF object only, produces column names with non-ASCI-chars, which works on Windows, but not on Unix-alike:

``` r
library(tidyverse)
#> Warning: Paket 'tibble' wurde unter R Version 4.0.3 erstellt
library(BayesFactor)
#> Lade nötiges Paket: coda
#> Lade nötiges Paket: Matrix
#> 
#> Attache Paket: 'Matrix'
#> The following objects are masked from 'package:tidyr':
#> 
#>     expand, pack, unpack
#> ************
#> Welcome to BayesFactor 0.9.12-4.2. If you have questions, please contact Richard Morey (richarddmorey@gmail.com).
#> 
#> Type BFManual() to open the manual.
#> ************
library(bayestestR)

# Setup data frame

df <- tibble(
  id = factor(rep(1:48, each = 4)),
  g = factor(rep(c("g1","g2","g3"), times = 16, each = 4)),
  s = factor(rep(c("s1","s2"), times = 48, each = 2)),
  b = factor(rep(c("b1","b2"), times = 96, each = 1)),
  y = rnorm(192,5,1) # Nonsensical for the current purposes
)

# Running Bayesian ANOVA

bf <- anovaBF(y ~ g*s*b + id,
              whichRandom = "id",
              data = df)   # disregard high numerical error, not recomputing here
#> Warning: data coerced from tibble to data frame

# Weighted posteriors

out <- BayesFactor::posterior(1 / bf[1], iterations = 10)

colnames(as.data.frame(out))
#>  [1] "mu"   "id5"  "id6"  "id7"  "id8"  "id9"  "id:"  "id;"  "id<"  "id=" 
#> [11] "id5Ð" "id5Ô" "id5Ø" "id5Ü" "id5à" "id5ä" "id5è" "id5ì" "id5ð" "id5ô"
#> [21] "id6Ð" "id6Ô" "id6Ø" "id6Ü" "id6à" "id6ä" "id6è" "id6ì" "id6ð" "id6ô"
#> [31] "id7Ð" "id7Ô" "id7Ø" "id7Ü" "id7à" "id7ä" "id7è" "id7ì" "id7ð" "id7ô"
#> [41] "id8Ð" "id8Ô" "id8Ø" "id8Ü" "id8à" "id8ä" "id8è" "id8ì" "id8ð" "sig2"
#> [51] "g_id"
```

<sup>Created on 2020-10-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


see also

``` r
library(tidyverse)
#> Warning: Paket 'tibble' wurde unter R Version 4.0.3 erstellt
library(BayesFactor)
#> Lade nötiges Paket: coda
#> Lade nötiges Paket: Matrix
#> 
#> Attache Paket: 'Matrix'
#> The following objects are masked from 'package:tidyr':
#> 
#>     expand, pack, unpack
#> ************
#> Welcome to BayesFactor 0.9.12-4.2. If you have questions, please contact Richard Morey (richarddmorey@gmail.com).
#> 
#> Type BFManual() to open the manual.
#> ************
library(bayestestR)

# Setup data frame

df <- tibble(
  id = factor(rep(1:48, each = 4)),
  g = factor(rep(c("g1","g2","g3"), times = 16, each = 4)),
  s = factor(rep(c("s1","s2"), times = 48, each = 2)),
  b = factor(rep(c("b1","b2"), times = 96, each = 1)),
  y = rnorm(192,5,1) # Nonsensical for the current purposes
)

# Running Bayesian ANOVA

bf <- anovaBF(y ~ g*s*b + id,
              whichRandom = "id",
              data = df)   # disregard high numerical error, not recomputing here
#> Warning: data coerced from tibble to data frame

# Weighted posteriors

out <- BayesFactor::posterior(1 / bf[1], iterations = 10)

cn <- colnames(as.data.frame(out))
iconv(cn, "UTF-8", "ASCII")
#>  [1] "mu"   "id5"  "id6"  "id7"  "id8"  "id9"  "id:"  "id;"  "id<"  "id=" 
#> [11] NA     NA     NA     NA     NA     NA     NA     NA     NA     NA    
#> [21] NA     NA     NA     NA     NA     NA     NA     NA     NA     NA    
#> [31] NA     NA     NA     NA     NA     NA     NA     NA     NA     NA    
#> [41] NA     NA     NA     NA     NA     NA     NA     NA     NA     "sig2"
#> [51] "g_id"
```

<sup>Created on 2020-10-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

But I'm not sure how to deal with this?

**Comment by mattansb** [comment] 2020-10-15 06:02
This is a BayesFactor level issue... :/

I'll open an issue over then, and hope this gets fixed.

**Comment by mattansb** [comment] 2020-10-15 06:04
Wait, can I add `iconv(cn, "UTF-8", "ASCII")` to fix the column names? Or will it not work either way?

**Comment by mattansb** [comment] 2020-10-15 06:04
Ah, it won't work :/

**Comment by mattansb** [comment] 2020-10-15 06:10
This also means that the random effects aren't actually matched across *all* models... Opened an issue on `BayesFactor`.

**Comment by richarddmorey** [comment] 2020-10-15 12:55
I'll check this out.

**Comment by richarddmorey** [comment] 2020-10-16 10:56
I can't reproduce this. Is it a locality issue? I'm running

```
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] dplyr_1.0.2            BayesFactor_0.9.12-4.3
[3] Matrix_1.2-18          coda_0.19-3           

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6       rstudioapi_0.11    magrittr_1.5      
 [4] tidyselect_1.1.0   lattice_0.20-41    R6_2.4.1          
 [7] rlang_0.4.7        fansi_0.4.1        pbapply_1.4-2     
[10] stringr_1.4.0      tools_4.0.0        parallel_4.0.0    
[13] grid_4.0.0         cli_2.0.2          ellipsis_0.3.1    
[16] MatrixModels_0.4-1 gtools_3.8.2       assertthat_0.2.1  
[19] tibble_3.0.3       lifecycle_0.2.0    crayon_1.3.4      
[22] purrr_0.3.4        vctrs_0.3.4        glue_1.4.2        
[25] stringi_1.4.6      compiler_4.0.0     pillar_1.4.6      
[28] generics_0.0.2     mvtnorm_1.1-1      pkgconfig_2.0.3  
```

**Comment by mattansb** [comment] 2020-10-16 11:15
You can't reproduce the `bayestestR` error? Or the different random effect names in the `BFBayesFactor`'s posteriors?

**Comment by richarddmorey** [comment] 2020-10-16 11:47
> You can't reproduce the `bayestestR` error? Or the different random effect names in the `BFBayesFactor`'s posteriors?

Sorry, the BayesFactor part shown by @strengejacke:

```
colnames(as.data.frame(out))
#>  [1] "mu"   "id5"  "id6"  "id7"  "id8"  "id9"  "id:"  "id;"  "id<"  "id=" 
#> [11] "id5Ð" "id5Ô" "id5Ø" "id5Ü" "id5à" "id5ä" "id5è" "id5ì" "id5ð" "id5ô"
#> [21] "id6Ð" "id6Ô" "id6Ø" "id6Ü" "id6à" "id6ä" "id6è" "id6ì" "id6ð" "id6ô"
#> [31] "id7Ð" "id7Ô" "id7Ø" "id7Ü" "id7à" "id7ä" "id7è" "id7ì" "id7ð" "id7ô"
#> [41] "id8Ð" "id8Ô" "id8Ø" "id8Ü" "id8à" "id8ä" "id8è" "id8ì" "id8ð" "sig2"
#> [51] "g_id"
```

I get (no weird characters):

```
> library(BayesFactor)
Loading required package: coda
Loading required package: Matrix
************
Welcome to BayesFactor 0.9.12-4.3. If you have questions, please contact Richard Morey (richarddmorey@gmail.com).

Type BFManual() to open the manual.
************
> set.seed(1234)
> 
> N <- 1e5
> 
> X <- rnorm(N)
> Y <- rnorm(N)
> 
> ttbf <- ttestBF(x = X, y = Y, mu = 0, rscale = "medium")
> 
> library(BayesFactor)
> 
> # Setup data frame
> df <- data.frame(
+   id = factor(rep(1:48, each = 4)),
+   b = factor(rep(c("b1","b2"), times = 96, each = 1)),
+   y = rnorm(192,5,1) # Nonsensical for the current purposes
+ )
> 
> # Running Bayesian ANOVA
> 
> bf <- anovaBF(y ~ b + id,
+               whichRandom = "id",
+               data = df)   # disregard high numerical error, not recomputing here
  |=========================================================| 100%
> 
> 
> out <- BayesFactor::posterior(1 / bf[1], iterations = 10)
0                                                                                                   %
|----|----|----|----|----|----|----|----|----|----|
**************************************************|
|
> colnames(as.data.frame(out))
 [1] "mu"   "id1"  "id2"  "id3"  "id4"  "id5"  "id6"  "id7"  "id8" 
[10] "id9"  "id10" "id11" "id12" "id13" "id14" "id15" "id16" "id17"
[19] "id18" "id19" "id20" "id21" "id22" "id23" "id24" "id25" "id26"
[28] "id27" "id28" "id29" "id30" "id31" "id32" "id33" "id34" "id35"
[37] "id36" "id37" "id38" "id39" "id40" "id41" "id42" "id43" "id44"
[46] "id45" "id46" "id47" "id48" "sig2" "g_id"
```

**Comment by mattansb** [comment] 2020-10-16 11:57
Ah... that is odd. 

# On mac

```R


> colnames(as.data.frame(out))
 [1] "mu"      "id5"     "id6"     "id7"     "id8"     "id9"     "id:"     "id;"     "id<"     "id="     "id5\xd0" "id5\xd4" "id5\xd8" "id5\xdc" "id5\xe0" "id5\xe4"
[17] "id5\xe8" "id5\xec" "id5\xf0" "id5\xf4" "id6\xd0" "id6\xd4" "id6\xd8" "id6\xdc" "id6\xe0" "id6\xe4" "id6\xe8" "id6\xec" "id6\xf0" "id6\xf4" "id7\xd0" "id7\xd4"
[33] "id7\xd8" "id7\xdc" "id7\xe0" "id7\xe4" "id7\xe8" "id7\xec" "id7\xf0" "id7\xf4" "id8\xd0" "id8\xd4" "id8\xd8" "id8\xdc" "id8\xe0" "id8\xe4" "id8\xe8" "id8\xec"
[49] "id8\xf0" "sig2"    "g_id"   
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] BayesFactor_0.9.12-4.2 coda_0.19-4            emmeans_1.5.1          lme4_1.1-23            Matrix_1.2-18          forcats_0.5.0         
 [7] stringr_1.4.0          dplyr_1.0.2            purrr_0.3.4            readr_1.4.0            tidyr_1.1.2            tibble_3.0.3          
[13] ggplot2_3.3.2          tidyverse_1.3.0        readbulk_1.1.3        

loaded via a namespace (and not attached):
  [1] TH.data_1.0-10      minqa_1.2.4         colorspace_1.4-1    ellipsis_0.3.1      rio_0.5.16          estimability_1.3    htmlTable_2.1.0    
  [8] fs_1.5.0            parameters_0.8.6    base64enc_0.1-3     rstudioapi_0.11     mice_3.11.0         MatrixModels_0.4-1  lubridate_1.7.9    
 [15] fansi_0.4.1         mvtnorm_1.1-1       xml2_1.3.2          codetools_0.2-16    splines_4.0.2       knitr_1.30          afex_0.28-0        
 [22] jsonlite_1.7.1      Formula_1.2-3       nloptr_1.2.2.2      packrat_0.5.0       broom_0.7.1         cluster_2.1.0       dbplyr_1.4.4       
 [29] png_0.1-7           finalfit_1.0.2      effectsize_0.3.3    httr_1.4.2          compiler_4.0.2      backports_1.1.10    assertthat_0.2.1   
 [36] Ckmeans.1d.dp_4.3.3 cli_2.1.0           htmltools_0.5.0     tools_4.0.2         lmerTest_3.1-2      gtable_0.3.0        glue_1.4.2         
 [43] reshape2_1.4.4      tinytex_0.26        Rcpp_1.0.5          carData_3.0-4       cellranger_1.1.0    vctrs_0.3.4         nlme_3.1-149       
 [50] gbRd_0.4-11         insight_0.9.6       xfun_0.18           rbibutils_1.3       rvest_0.3.6         openxlsx_4.2.2      lifecycle_0.2.0    
 [57] gtools_3.8.2        statmod_1.4.34      MASS_7.3-53         zoo_1.8-8           scales_1.1.1        hms_0.5.3           parallel_4.0.2     
 [64] sandwich_3.0-0      RColorBrewer_1.1-2  curl_4.3            pbapply_1.4-3       gridExtra_2.3       rpart_4.1-15        latticeExtra_0.6-29
 [71] stringi_1.5.3       bayestestR_0.7.2    checkmate_2.0.0     boot_1.3-25         zip_2.1.1           Rdpack_2.0          rlang_0.4.8        
 [78] pkgconfig_2.0.3     lattice_0.20-41     htmlwidgets_1.5.2   tidyselect_1.1.0    plyr_1.8.6          magrittr_1.5        R6_2.4.1           
 [85] generics_0.0.2      Hmisc_4.4-1         multcomp_1.4-14     DBI_1.1.0           withr_2.3.0         pillar_1.4.6        haven_2.3.1        
 [92] foreign_0.8-80      survival_3.2-7      abind_1.4-5         nnet_7.3-14         modelr_0.1.8        crayon_1.3.4        car_3.0-10         
 [99] utf8_1.1.4          jpeg_0.1-8.1        grid_4.0.2          readxl_1.3.1        data.table_1.13.0   blob_1.2.1          reprex_0.3.0       
[106] digest_0.6.25       xtable_1.8-4        numDeriv_2016.8-1.1 munsell_0.5.0      
```

# On windows

```R
> colnames(as.data.frame(out))
 [1] "mu"   "id5"  "id6"  "id7"  "id8"  "id9"  "id:"  "id;"  "id<"  "id="  "id5Ð" "id5Ô" "id5Ø" "id5Ü"
[15] "id5à" "id5ä" "id5è" "id5ì" "id5ð" "id5ô" "id6Ð" "id6Ô" "id6Ø" "id6Ü" "id6à" "id6ä" "id6è" "id6ì"
[29] "id6ð" "id6ô" "id7Ð" "id7Ô" "id7Ø" "id7Ü" "id7à" "id7ä" "id7è" "id7ì" "id7ð" "id7ô" "id8Ð" "id8Ô"
[43] "id8Ø" "id8Ü" "id8à" "id8ä" "id8è" "id8ì" "id8ð" "sig2" "g_id"
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    
system code page: 1255

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BayesFactor_0.9.12-4.2 Matrix_1.2-18          coda_0.19-4           

loaded via a namespace (and not attached):
 [1] compiler_4.0.2     magrittr_1.5       parallel_4.0.2     tools_4.0.2        yaml_2.2.1        
 [6] pbapply_1.4-3      MatrixModels_0.4-1 Rcpp_1.0.5         mvtnorm_1.1-1      stringi_1.5.3     
[11] grid_4.0.2         stringr_1.4.0      gtools_3.8.2       lattice_0.20-41  
```

**Comment by richarddmorey** [comment] 2020-10-16 12:44
Ah, I think Jonathon Love fixed that here: https://github.com/richarddmorey/BayesFactor/commit/6517a6d3a1de31881988a59e403dfbbc40a58434 - Can you install the development version of BayesFactor and see if that fixes it?

**Comment by mattansb** [comment] 2020-10-16 15:31
The Unicode problem is solved on the dev version, yes, but not the non-matchingness across the models (due to the dashes):

``` r
library(BayesFactor)
#> Loading required package: coda
#> Loading required package: Matrix
#> ************
#> Welcome to BayesFactor 0.9.12-4.2. If you have questions, please contact Richard Morey (richarddmorey@gmail.com).
#> 
#> Type BFManual() to open the manual.
#> ************

df <- data.frame(
  id = factor(rep(1:48, each = 4)),
  b = factor(rep(1:2, times = 96, each = 1)),
  y = rnorm(192, 5, 1)
) # Nonsensical for the current purposes)


bf <- anovaBF(y ~ b + id,
              whichRandom = "id",
              data = df)

out_den <- BayesFactor::posterior(1 / bf[1], iterations = 10)
colnames(out_den)
#>  [1] "mu"   "id1"  "id2"  "id3"  "id4"  "id5"  "id6"  "id7"  "id8"  "id9" 
#> [11] "id10" "id11" "id12" "id13" "id14" "id15" "id16" "id17" "id18" "id19"
#> [21] "id20" "id21" "id22" "id23" "id24" "id25" "id26" "id27" "id28" "id29"
#> [31] "id30" "id31" "id32" "id33" "id34" "id35" "id36" "id37" "id38" "id39"
#> [41] "id40" "id41" "id42" "id43" "id44" "id45" "id46" "id47" "id48" "sig2"
#> [51] "g_id"


out_num <- BayesFactor::posterior(bf[1], iterations = 10)
colnames(out_num)
#>  [1] "mu"    "b-1"   "b-2"   "id-1"  "id-2"  "id-3"  "id-4"  "id-5"  "id-6" 
#> [10] "id-7"  "id-8"  "id-9"  "id-10" "id-11" "id-12" "id-13" "id-14" "id-15"
#> [19] "id-16" "id-17" "id-18" "id-19" "id-20" "id-21" "id-22" "id-23" "id-24"
#> [28] "id-25" "id-26" "id-27" "id-28" "id-29" "id-30" "id-31" "id-32" "id-33"
#> [37] "id-34" "id-35" "id-36" "id-37" "id-38" "id-39" "id-40" "id-41" "id-42"
#> [46] "id-43" "id-44" "id-45" "id-46" "id-47" "id-48" "sig2"  "g_b"   "g_id"
```

<sup>Created on 2020-10-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by richarddmorey** [comment] 2020-10-17 09:15
ok, I think this is fixed in the development version. Can you try it?

**Comment by mattansb** [comment] 2020-10-17 10:38
Yes, this solved it! Thanks Richard!
Are there any plans to update `BayesFactor` on CRAN in the near future?

**Comment by richarddmorey** [comment] 2020-10-17 11:17
> Yes, this solved it! Thanks Richard!
> Are there any plans to update `BayesFactor` on CRAN in the near future?

I'll push an update specifically for this and the special character issue. Maybe sometime in the next week?

**Comment by mattansb** [comment] 2020-10-17 11:19
Great, thanks again for you quick work!

---

@nahorp this should be resolved when using the new version of `BayesFactor`.
Closing this.

**Closed by mattansb** 2020-10-17 11:19 UTC
Labels: wontfix :no_entry_sign:

**Comment by nahorp** [comment] 2020-10-19 01:31
Thank you @richarddmorey and @mattansb, this now works.
