### ISSUE TITLE
Cran update

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#456] opened 2021-08-19 09:41 UTC
It's that time of the year again

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_bayestestR.html>.

Please correct before 2021-09-02 to safely retain your package on CRAN.

**Comment by mattansb** [comment] 2021-08-19 09:54
# 1. https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/bayestestR-00check.html

```
 ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure (test-map_estimate.R:30:7): map_estimate ────────────────────────────
  map_estimate(m, effects = "all", component = "all")$Parameter (`actual`) not equal to c(...) (`expected`).
  
       actual | expected
   [1] "b_Intercept" | "b_Intercept" [1]
   [2] "b_child" | "b_child" [2]
   [3] "b_camper" | "b_camper" [3]
   [4] "r_persons[1,Intercept]" - "r_persons.1.Intercept." [4]
   [5] "r_persons[2,Intercept]" - "r_persons.2.Intercept." [5]
   [6] "r_persons[3,Intercept]" - "r_persons.3.Intercept." [6]
   [7] "r_persons[4,Intercept]" - "r_persons.4.Intercept." [7]
   [8] "sd_persons__Intercept" | "sd_persons__Intercept" [8]
   [9] "b_zi_Intercept" | "b_zi_Intercept" [9]
  [10] "b_zi_child" | "b_zi_child" [10]
   ... ... ... and 6 more ...
```

Seems like `insight` is using the new naming scheme in `brms`, while this test is expecting the old naming scheme.... But why would that only be failing on 1 system?

# 2. https://www.r-project.org/nosvn/R.check/r-release-macos-arm64/bayestestR-00check.html

Fonts?????

**Comment by strengejacke** [comment] 2021-08-19 12:46
> Seems like insight is using the new naming scheme in brms

Unlikely that's the cause, because in this case, reverse dependency checks shouldn't have passed. I guess it's related to the new _brms_ update, which probably doesn't allow to return old naming schemes.

**Comment by strengejacke** [comment] 2021-08-19 13:39
> But why would that only be failing on 1 system?

brms-update has not yet arrived on all systems:
https://cran.r-project.org/web/checks/check_results_brms.html

The reason is that the `optional` argument in `as.data.frame.brmsfit()` no longer allows to return the old naming scheme:

``` r
library(brms)
zinb <- read.csv("http://stats.idre.ucla.edu/stat/data/fish.csv")
set.seed(123)

m <- brm(
  bf(count ~ child + camper + (1 | persons), zi ~ child + camper + (1 | persons)),
  data = zinb,
  family = zero_inflated_poisson(),
  chains = 1,
  iter = 500
)

colnames(as.data.frame(m, optional = FALSE))
#>  [1] "b_Intercept"                "b_zi_Intercept"            
#>  [3] "b_child"                    "b_camper"                  
#>  [5] "b_zi_child"                 "b_zi_camper"               
#>  [7] "sd_persons__Intercept"      "sd_persons__zi_Intercept"  
#>  [9] "r_persons[1,Intercept]"     "r_persons[2,Intercept]"    
#> [11] "r_persons[3,Intercept]"     "r_persons[4,Intercept]"    
#> [13] "r_persons__zi[1,Intercept]" "r_persons__zi[2,Intercept]"
#> [15] "r_persons__zi[3,Intercept]" "r_persons__zi[4,Intercept]"
#> [17] "lp__"
colnames(as.data.frame(m, optional = TRUE))
#>  [1] "b_Intercept"                "b_zi_Intercept"            
#>  [3] "b_child"                    "b_camper"                  
#>  [5] "b_zi_child"                 "b_zi_camper"               
#>  [7] "sd_persons__Intercept"      "sd_persons__zi_Intercept"  
#>  [9] "r_persons[1,Intercept]"     "r_persons[2,Intercept]"    
#> [11] "r_persons[3,Intercept]"     "r_persons[4,Intercept]"    
#> [13] "r_persons__zi[1,Intercept]" "r_persons__zi[2,Intercept]"
#> [15] "r_persons__zi[3,Intercept]" "r_persons__zi[4,Intercept]"
#> [17] "lp__"
```

I'm not sure which packages are all affected, I guess mainly _insight_, since the regular expressions probably no longer work as intended...

**Comment by strengejacke** [comment] 2021-08-19 13:53
> Fonts?????

I think the error is

Error: processing vignette 'region_of_practical_equivalence.Rmd' failed with diagnostics:
polygon edge not found

**Comment by strengejacke** [comment] 2021-08-19 14:36
Does anybody know what these strange parameters like `r_1[2,1]` or `z_1[1,1]` or `L_1[1,2]` are? I guess, these are related to the `age` predictor, but I'm not sure about the pattern. I guess these can be removed from the output from `find_parameters()`.

``` r
library(brms)
#> Loading required package: Rcpp
#> Loading 'brms' package (version 2.16.0). Useful instructions
#> can be found by typing help('brms'). A more detailed introduction
#> to the package is available through vignette('brms_overview').
#> 
#> Attaching package: 'brms'
#> The following object is masked from 'package:stats':
#> 
#>     ar

bprior1 <- prior(student_t(5, 0, 10), class = b) + prior(cauchy(0, 2), class = sd)
m8 <- brm(
  count ~ Age + Base * Trt + (1 + Age | patient),
  data = epilepsy,
  family = poisson(),
  prior = bprior1,
  chains = 1,
  iter = 500
)

colnames(as.data.frame(m8))
#>   [1] "b_Intercept"                 "b_Age"                      
#>   [3] "b_Base"                      "b_Trt1"                     
#>   [5] "b_Base:Trt1"                 "sd_patient__Intercept"      
#>   [7] "sd_patient__Age"             "cor_patient__Intercept__Age"
#>   [9] "r_patient[1,Intercept]"      "r_patient[2,Intercept]"     
#>  [11] "r_patient[3,Intercept]"      "r_patient[4,Intercept]"     
#>  [13] "r_patient[5,Intercept]"      "r_patient[6,Intercept]"     
#>  [15] "r_patient[7,Intercept]"      "r_patient[8,Intercept]"     
#>  [17] "r_patient[9,Intercept]"      "r_patient[10,Intercept]"    
#>  [19] "r_patient[11,Intercept]"     "r_patient[12,Intercept]"    
#>  [21] "r_patient[13,Intercept]"     "r_patient[14,Intercept]"    
#>  [23] "r_patient[15,Intercept]"     "r_patient[16,Intercept]"    
#>  [25] "r_patient[17,Intercept]"     "r_patient[18,Intercept]"    
#>  [27] "r_patient[19,Intercept]"     "r_patient[20,Intercept]"    
#>  [29] "r_patient[21,Intercept]"     "r_patient[22,Intercept]"    
#>  [31] "r_patient[23,Intercept]"     "r_patient[24,Intercept]"    
#>  [33] "r_patient[25,Intercept]"     "r_patient[26,Intercept]"    
#>  [35] "r_patient[27,Intercept]"     "r_patient[28,Intercept]"    
#>  [37] "r_patient[29,Intercept]"     "r_patient[30,Intercept]"    
#>  [39] "r_patient[31,Intercept]"     "r_patient[32,Intercept]"    
#>  [41] "r_patient[33,Intercept]"     "r_patient[34,Intercept]"    
#>  [43] "r_patient[35,Intercept]"     "r_patient[36,Intercept]"    
#>  [45] "r_patient[37,Intercept]"     "r_patient[38,Intercept]"    
#>  [47] "r_patient[39,Intercept]"     "r_patient[40,Intercept]"    
#>  [49] "r_patient[41,Intercept]"     "r_patient[42,Intercept]"    
#>  [51] "r_patient[43,Intercept]"     "r_patient[44,Intercept]"    
#>  [53] "r_patient[45,Intercept]"     "r_patient[46,Intercept]"    
#>  [55] "r_patient[47,Intercept]"     "r_patient[48,Intercept]"    
#>  [57] "r_patient[49,Intercept]"     "r_patient[50,Intercept]"    
#>  [59] "r_patient[51,Intercept]"     "r_patient[52,Intercept]"    
#>  [61] "r_patient[53,Intercept]"     "r_patient[54,Intercept]"    
#>  [63] "r_patient[55,Intercept]"     "r_patient[56,Intercept]"    
#>  [65] "r_patient[57,Intercept]"     "r_patient[58,Intercept]"    
#>  [67] "r_patient[59,Intercept]"     "r_patient[1,Age]"           
#>  [69] "r_patient[2,Age]"            "r_patient[3,Age]"           
#>  [71] "r_patient[4,Age]"            "r_patient[5,Age]"           
#>  [73] "r_patient[6,Age]"            "r_patient[7,Age]"           
#>  [75] "r_patient[8,Age]"            "r_patient[9,Age]"           
#>  [77] "r_patient[10,Age]"           "r_patient[11,Age]"          
#>  [79] "r_patient[12,Age]"           "r_patient[13,Age]"          
#>  [81] "r_patient[14,Age]"           "r_patient[15,Age]"          
#>  [83] "r_patient[16,Age]"           "r_patient[17,Age]"          
#>  [85] "r_patient[18,Age]"           "r_patient[19,Age]"          
#>  [87] "r_patient[20,Age]"           "r_patient[21,Age]"          
#>  [89] "r_patient[22,Age]"           "r_patient[23,Age]"          
#>  [91] "r_patient[24,Age]"           "r_patient[25,Age]"          
#>  [93] "r_patient[26,Age]"           "r_patient[27,Age]"          
#>  [95] "r_patient[28,Age]"           "r_patient[29,Age]"          
#>  [97] "r_patient[30,Age]"           "r_patient[31,Age]"          
#>  [99] "r_patient[32,Age]"           "r_patient[33,Age]"          
#> [101] "r_patient[34,Age]"           "r_patient[35,Age]"          
#> [103] "r_patient[36,Age]"           "r_patient[37,Age]"          
#> [105] "r_patient[38,Age]"           "r_patient[39,Age]"          
#> [107] "r_patient[40,Age]"           "r_patient[41,Age]"          
#> [109] "r_patient[42,Age]"           "r_patient[43,Age]"          
#> [111] "r_patient[44,Age]"           "r_patient[45,Age]"          
#> [113] "r_patient[46,Age]"           "r_patient[47,Age]"          
#> [115] "r_patient[48,Age]"           "r_patient[49,Age]"          
#> [117] "r_patient[50,Age]"           "r_patient[51,Age]"          
#> [119] "r_patient[52,Age]"           "r_patient[53,Age]"          
#> [121] "r_patient[54,Age]"           "r_patient[55,Age]"          
#> [123] "r_patient[56,Age]"           "r_patient[57,Age]"          
#> [125] "r_patient[58,Age]"           "r_patient[59,Age]"          
#> [127] "lp__"
```

<sup>Created on 2021-08-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment] 2021-08-19 14:51
ok, why does the reprex output (see hidden comment above) and my console output differ, although I have started a clean session?

![image](https://user-images.githubusercontent.com/26301769/130090671-0c13fe85-c5db-47a8-95b3-1292c689c85e.png)

**Comment by mattansb** [comment] 2021-08-19 15:01
It's a flattened random effects matrix.

So say `y ~ (1 + a | id) + (1 + b + h | gr)`, you have a "column" for `1` and a column for `a`, and a row for each `id`, and a "column" for `1`, `b`, and `h` and a row for each `gr`.
So you can index a value as `r_id[1,Intercept]` for the first `id`'s intercept.... or `r_gr[30,h]` as the 30th's `gr`'s `h` slope... etc..

**Comment by strengejacke** [comment] 2021-08-19 15:22
yes, but the output in my console (left in the picture) returns > 300 columns for the data frame (including those columns from the reprex on the right), while the reprex only returns the expected ~ 200 columns.

**Comment by strengejacke** [comment] 2021-08-19 15:50
See https://github.com/easystats/insight/runs/3372992291#step:10:3535

**Comment by strengejacke** [comment] 2021-08-20 07:32
Can you please check what this code returns for you?

```r
library(brms)

bprior1 <- prior(student_t(5, 0, 10), class = b) + prior(cauchy(0, 2), class = sd)
m8 <- brm(
  count ~ Age + Base * Trt + (1 + Age | patient),
  data = epilepsy,
  family = poisson(),
  prior = bprior1,
  chains = 1,
  iter = 500
)

colnames(as.data.frame(m8))
```

That might be the crucial point to resolve in order to fix the errors in _bayestestR_.

**Comment by mattansb** [comment] 2021-08-20 07:55
```
  [1] "b_Intercept"                 "b_Age"                      
  [3] "b_Base"                      "b_Trt1"                     
  [5] "b_Base:Trt1"                 "sd_patient__Intercept"      
  [7] "sd_patient__Age"             "cor_patient__Intercept__Age"
  [9] "Intercept"                   "r_1[1,1]"                   
 [11] "r_1[2,1]"                    "r_1[3,1]"                   
 [13] "r_1[4,1]"                    "r_1[5,1]"                   
 [15] "r_1[6,1]"                    "r_1[7,1]"                   
 [17] "r_1[8,1]"                    "r_1[9,1]"                   
 [19] "r_1[10,1]"                   "r_1[11,1]"                  
 [21] "r_1[12,1]"                   "r_1[13,1]"                  
 [23] "r_1[14,1]"                   "r_1[15,1]"                  
 [25] "r_1[16,1]"                   "r_1[17,1]"                  
 [27] "r_1[18,1]"                   "r_1[19,1]"                  
 [29] "r_1[20,1]"                   "r_1[21,1]"                  
 [31] "r_1[22,1]"                   "r_1[23,1]"                  
 [33] "r_1[24,1]"                   "r_1[25,1]"                  
 [35] "r_1[26,1]"                   "r_1[27,1]"                  
 [37] "r_1[28,1]"                   "r_1[29,1]"                  
 [39] "r_1[30,1]"                   "r_1[31,1]"                  
 [41] "r_1[32,1]"                   "r_1[33,1]"                  
 [43] "r_1[34,1]"                   "r_1[35,1]"                  
 [45] "r_1[36,1]"                   "r_1[37,1]"                  
 [47] "r_1[38,1]"                   "r_1[39,1]"                  
 [49] "r_1[40,1]"                   "r_1[41,1]"                  
 [51] "r_1[42,1]"                   "r_1[43,1]"                  
 [53] "r_1[44,1]"                   "r_1[45,1]"                  
 [55] "r_1[46,1]"                   "r_1[47,1]"                  
 [57] "r_1[48,1]"                   "r_1[49,1]"                  
 [59] "r_1[50,1]"                   "r_1[51,1]"                  
 [61] "r_1[52,1]"                   "r_1[53,1]"                  
 [63] "r_1[54,1]"                   "r_1[55,1]"                  
 [65] "r_1[56,1]"                   "r_1[57,1]"                  
 [67] "r_1[58,1]"                   "r_1[59,1]"                  
 [69] "r_1[1,2]"                    "r_1[2,2]"                   
 [71] "r_1[3,2]"                    "r_1[4,2]"                   
 [73] "r_1[5,2]"                    "r_1[6,2]"                   
 [75] "r_1[7,2]"                    "r_1[8,2]"                   
 [77] "r_1[9,2]"                    "r_1[10,2]"                  
 [79] "r_1[11,2]"                   "r_1[12,2]"                  
 [81] "r_1[13,2]"                   "r_1[14,2]"                  
 [83] "r_1[15,2]"                   "r_1[16,2]"                  
 [85] "r_1[17,2]"                   "r_1[18,2]"                  
 [87] "r_1[19,2]"                   "r_1[20,2]"                  
 [89] "r_1[21,2]"                   "r_1[22,2]"                  
 [91] "r_1[23,2]"                   "r_1[24,2]"                  
 [93] "r_1[25,2]"                   "r_1[26,2]"                  
 [95] "r_1[27,2]"                   "r_1[28,2]"                  
 [97] "r_1[29,2]"                   "r_1[30,2]"                  
 [99] "r_1[31,2]"                   "r_1[32,2]"                  
[101] "r_1[33,2]"                   "r_1[34,2]"                  
[103] "r_1[35,2]"                   "r_1[36,2]"                  
[105] "r_1[37,2]"                   "r_1[38,2]"                  
[107] "r_1[39,2]"                   "r_1[40,2]"                  
[109] "r_1[41,2]"                   "r_1[42,2]"                  
[111] "r_1[43,2]"                   "r_1[44,2]"                  
[113] "r_1[45,2]"                   "r_1[46,2]"                  
[115] "r_1[47,2]"                   "r_1[48,2]"                  
[117] "r_1[49,2]"                   "r_1[50,2]"                  
[119] "r_1[51,2]"                   "r_1[52,2]"                  
[121] "r_1[53,2]"                   "r_1[54,2]"                  
[123] "r_1[55,2]"                   "r_1[56,2]"                  
[125] "r_1[57,2]"                   "r_1[58,2]"                  
[127] "r_1[59,2]"                   "r_patient[1,Intercept]"     
[129] "r_patient[2,Intercept]"      "r_patient[3,Intercept]"     
[131] "r_patient[4,Intercept]"      "r_patient[5,Intercept]"     
[133] "r_patient[6,Intercept]"      "r_patient[7,Intercept]"     
[135] "r_patient[8,Intercept]"      "r_patient[9,Intercept]"     
[137] "r_patient[10,Intercept]"     "r_patient[11,Intercept]"    
[139] "r_patient[12,Intercept]"     "r_patient[13,Intercept]"    
[141] "r_patient[14,Intercept]"     "r_patient[15,Intercept]"    
[143] "r_patient[16,Intercept]"     "r_patient[17,Intercept]"    
[145] "r_patient[18,Intercept]"     "r_patient[19,Intercept]"    
[147] "r_patient[20,Intercept]"     "r_patient[21,Intercept]"    
[149] "r_patient[22,Intercept]"     "r_patient[23,Intercept]"    
[151] "r_patient[24,Intercept]"     "r_patient[25,Intercept]"    
[153] "r_patient[26,Intercept]"     "r_patient[27,Intercept]"    
[155] "r_patient[28,Intercept]"     "r_patient[29,Intercept]"    
[157] "r_patient[30,Intercept]"     "r_patient[31,Intercept]"    
[159] "r_patient[32,Intercept]"     "r_patient[33,Intercept]"    
[161] "r_patient[34,Intercept]"     "r_patient[35,Intercept]"    
[163] "r_patient[36,Intercept]"     "r_patient[37,Intercept]"    
[165] "r_patient[38,Intercept]"     "r_patient[39,Intercept]"    
[167] "r_patient[40,Intercept]"     "r_patient[41,Intercept]"    
[169] "r_patient[42,Intercept]"     "r_patient[43,Intercept]"    
[171] "r_patient[44,Intercept]"     "r_patient[45,Intercept]"    
[173] "r_patient[46,Intercept]"     "r_patient[47,Intercept]"    
[175] "r_patient[48,Intercept]"     "r_patient[49,Intercept]"    
[177] "r_patient[50,Intercept]"     "r_patient[51,Intercept]"    
[179] "r_patient[52,Intercept]"     "r_patient[53,Intercept]"    
[181] "r_patient[54,Intercept]"     "r_patient[55,Intercept]"    
[183] "r_patient[56,Intercept]"     "r_patient[57,Intercept]"    
[185] "r_patient[58,Intercept]"     "r_patient[59,Intercept]"    
[187] "r_patient[1,Age]"            "r_patient[2,Age]"           
[189] "r_patient[3,Age]"            "r_patient[4,Age]"           
[191] "r_patient[5,Age]"            "r_patient[6,Age]"           
[193] "r_patient[7,Age]"            "r_patient[8,Age]"           
[195] "r_patient[9,Age]"            "r_patient[10,Age]"          
[197] "r_patient[11,Age]"           "r_patient[12,Age]"          
[199] "r_patient[13,Age]"           "r_patient[14,Age]"          
[201] "r_patient[15,Age]"           "r_patient[16,Age]"          
[203] "r_patient[17,Age]"           "r_patient[18,Age]"          
[205] "r_patient[19,Age]"           "r_patient[20,Age]"          
[207] "r_patient[21,Age]"           "r_patient[22,Age]"          
[209] "r_patient[23,Age]"           "r_patient[24,Age]"          
[211] "r_patient[25,Age]"           "r_patient[26,Age]"          
[213] "r_patient[27,Age]"           "r_patient[28,Age]"          
[215] "r_patient[29,Age]"           "r_patient[30,Age]"          
[217] "r_patient[31,Age]"           "r_patient[32,Age]"          
[219] "r_patient[33,Age]"           "r_patient[34,Age]"          
[221] "r_patient[35,Age]"           "r_patient[36,Age]"          
[223] "r_patient[37,Age]"           "r_patient[38,Age]"          
[225] "r_patient[39,Age]"           "r_patient[40,Age]"          
[227] "r_patient[41,Age]"           "r_patient[42,Age]"          
[229] "r_patient[43,Age]"           "r_patient[44,Age]"          
[231] "r_patient[45,Age]"           "r_patient[46,Age]"          
[233] "r_patient[47,Age]"           "r_patient[48,Age]"          
[235] "r_patient[49,Age]"           "r_patient[50,Age]"          
[237] "r_patient[51,Age]"           "r_patient[52,Age]"          
[239] "r_patient[53,Age]"           "r_patient[54,Age]"          
[241] "r_patient[55,Age]"           "r_patient[56,Age]"          
[243] "r_patient[57,Age]"           "r_patient[58,Age]"          
[245] "r_patient[59,Age]"           "lp__"                       
[247] "z_1[1,1]"                    "z_1[2,1]"                   
[249] "z_1[1,2]"                    "z_1[2,2]"                   
[251] "z_1[1,3]"                    "z_1[2,3]"                   
[253] "z_1[1,4]"                    "z_1[2,4]"                   
[255] "z_1[1,5]"                    "z_1[2,5]"                   
[257] "z_1[1,6]"                    "z_1[2,6]"                   
[259] "z_1[1,7]"                    "z_1[2,7]"                   
[261] "z_1[1,8]"                    "z_1[2,8]"                   
[263] "z_1[1,9]"                    "z_1[2,9]"                   
[265] "z_1[1,10]"                   "z_1[2,10]"                  
[267] "z_1[1,11]"                   "z_1[2,11]"                  
[269] "z_1[1,12]"                   "z_1[2,12]"                  
[271] "z_1[1,13]"                   "z_1[2,13]"                  
[273] "z_1[1,14]"                   "z_1[2,14]"                  
[275] "z_1[1,15]"                   "z_1[2,15]"                  
[277] "z_1[1,16]"                   "z_1[2,16]"                  
[279] "z_1[1,17]"                   "z_1[2,17]"                  
[281] "z_1[1,18]"                   "z_1[2,18]"                  
[283] "z_1[1,19]"                   "z_1[2,19]"                  
[285] "z_1[1,20]"                   "z_1[2,20]"                  
[287] "z_1[1,21]"                   "z_1[2,21]"                  
[289] "z_1[1,22]"                   "z_1[2,22]"                  
[291] "z_1[1,23]"                   "z_1[2,23]"                  
[293] "z_1[1,24]"                   "z_1[2,24]"                  
[295] "z_1[1,25]"                   "z_1[2,25]"                  
[297] "z_1[1,26]"                   "z_1[2,26]"                  
[299] "z_1[1,27]"                   "z_1[2,27]"                  
[301] "z_1[1,28]"                   "z_1[2,28]"                  
[303] "z_1[1,29]"                   "z_1[2,29]"                  
[305] "z_1[1,30]"                   "z_1[2,30]"                  
[307] "z_1[1,31]"                   "z_1[2,31]"                  
[309] "z_1[1,32]"                   "z_1[2,32]"                  
[311] "z_1[1,33]"                   "z_1[2,33]"                  
[313] "z_1[1,34]"                   "z_1[2,34]"                  
[315] "z_1[1,35]"                   "z_1[2,35]"                  
[317] "z_1[1,36]"                   "z_1[2,36]"                  
[319] "z_1[1,37]"                   "z_1[2,37]"                  
[321] "z_1[1,38]"                   "z_1[2,38]"                  
[323] "z_1[1,39]"                   "z_1[2,39]"                  
[325] "z_1[1,40]"                   "z_1[2,40]"                  
[327] "z_1[1,41]"                   "z_1[2,41]"                  
[329] "z_1[1,42]"                   "z_1[2,42]"                  
[331] "z_1[1,43]"                   "z_1[2,43]"                  
[333] "z_1[1,44]"                   "z_1[2,44]"                  
[335] "z_1[1,45]"                   "z_1[2,45]"                  
[337] "z_1[1,46]"                   "z_1[2,46]"                  
[339] "z_1[1,47]"                   "z_1[2,47]"                  
[341] "z_1[1,48]"                   "z_1[2,48]"                  
[343] "z_1[1,49]"                   "z_1[2,49]"                  
[345] "z_1[1,50]"                   "z_1[2,50]"                  
[347] "z_1[1,51]"                   "z_1[2,51]"                  
[349] "z_1[1,52]"                   "z_1[2,52]"                  
[351] "z_1[1,53]"                   "z_1[2,53]"                  
[353] "z_1[1,54]"                   "z_1[2,54]"                  
[355] "z_1[1,55]"                   "z_1[2,55]"                  
[357] "z_1[1,56]"                   "z_1[2,56]"                  
[359] "z_1[1,57]"                   "z_1[2,57]"                  
[361] "z_1[1,58]"                   "z_1[2,58]"                  
[363] "z_1[1,59]"                   "z_1[2,59]"                  
[365] "L_1[1,1]"                    "L_1[2,1]"                   
[367] "L_1[1,2]"                    "L_1[2,2]"                   
[369] "Cor_1[1,1]"                  "Cor_1[2,1]"                 
[371] "Cor_1[1,2]"                  "Cor_1[2,2]" 
```

**Comment by strengejacke** [comment] 2021-08-20 20:35
Same for me. Can you explain the r_<number>[] columns? I'm not sure why these suddenly appear.

**Comment by bwiernik** [comment] 2021-08-20 20:36
Those are the estimated random effects for the parameter for each group

**Comment by strengejacke** [comment] 2021-08-21 08:37
I understand the meaning of these parameters:
`r_patient[58,Intercept]`
`r_patient[32,Age]`

But these parameters seem to be new and were not included formerly (i.e. in older brms versions?) in that model, at least I can't explain why these parameters didn't show up before:

`r_1[9,2]`
`z_1[1,33]`
`L_1[1,1]`

**Comment by DominiqueMakowski** [comment] 2021-08-21 08:40
> But these parameters seem to be new and were not included formerly

Yes I think they didn't appear under this form previously (without the brackets i think)

**Comment by strengejacke** [comment] 2021-08-21 08:51
Anyway, since [`optional = FALSE`](https://github.com/easystats/bayestestR/issues/456#issuecomment-901924212) no longer seems to work, I'm revising the regular expression patterns in _insight_. Tests in _bayestestR_ can then be revised accordingly. I haven't checked, but I don't think we have many instances in _bayestestR_ where we need to fix the regex-patterns when capturing brms-parameters.

**Comment by DominiqueMakowski** [comment] 2021-08-21 08:55
yes, I think most of the API relies on insight's find_parameters, so if it works there then most of it should work here

**Comment by strengejacke** [comment] 2021-08-23 08:11
If you look at the following output, the results under the part `# Random effects` and `# Random effects Intercept: patient` seem to be identical. It looks likes the new parameters that `as.data.frame()` returns from the latest update includes redundant parameters?

```r
m7 <- suppressWarnings(insight::download_model("brms_mixed_8"))
parameters::model_parameters(m7, effects = "all", component = "all", group_level = TRUE)
```

_insight_ is fixed now. I think, the only thing that remains is to filter out those redundant parameters from `find_parameters()` and `clean_parameters()`.

**Comment by strengejacke** [comment] 2021-08-23 12:52
Ok, I think all issues are resolved. You could check after updating _insight_ from GitHub, and fix the tests (mostly renaming, I think). If everything works, we can submit _insight_ and then _bayestestR_ to CRAN.

**Comment by strengejacke** [comment] 2021-08-24 08:24
Looks like the latest _insight_ changes resolve the _bayestestR_ issues.

**Comment by DominiqueMakowski** [comment] 2021-08-24 08:36
awesome, should I submit bayestestR?

**Comment by strengejacke** [comment] 2021-08-24 08:58
Need to submit _insight_ first. Since all tests seem to pass, will do this today or tomorrow. Maybe you can also check _bayestestR_ locally with the latest dev of _insight_?

**Comment by IndrajeetPatil** [comment] 2021-08-24 09:21
You can submit datawizard update and when I get an email, I will approve the submission.

**Comment by strengejacke** [comment] 2021-08-24 11:33
Ok, I'll do this then now, ok everyone?

**Comment by bwiernik** [comment] 2021-08-24 21:53
Were you able to submit @strengejacke or did you get a "Submission team on vacation" message?

**Comment by strengejacke** [comment] 2021-08-25 06:23
Yes, submissions are suspended until Sep 1st. It's a bit strange to set the deadline to 2nd September then, but maybe we can mail the CRAN team and explain that we have fixed all issues and are prepared to submit?

**Comment by DominiqueMakowski** [comment] 2021-08-25 07:00
> maybe we can mail the CRAN team and explain that we have fixed all issues and are prepared to submit?

email like now or mention that it's an urgent update given the deadline on the 1st?

**Comment by strengejacke** [comment] 2021-09-01 06:18
@DominiqueMakowski have you already submitted?

**Comment by DominiqueMakowski** [comment] 2021-09-01 07:44
not yet I'm waiting for the reopening

**Comment by bwiernik** [comment] 2021-09-01 10:15
Can we get datawizard submitted as soon as possible so I can submit correlation?

**Comment by strengejacke** [comment] 2021-09-01 11:07
Yes, I'll do this - or is @IndrajeetPatil already back on board?

**Comment by IndrajeetPatil** [comment] 2021-09-01 11:08
Yepp, submitting it now.

**Comment by DominiqueMakowski** [comment] 2021-09-01 13:33
do I wait 'til tomorrow (i.e., European night) for bayestestR or now?

**Comment by IndrajeetPatil** [comment] 2021-09-01 13:37
`{datawizard}` is still pending the pretest. There seems to be a traffic jam with so many people submitting their updates after the holidays.

**Comment by strengejacke** [comment] 2021-09-01 17:31
> do I wait 'til tomorrow (i.e., European night) for bayestestR or now?

I think _bayestestR_ needs _insight_ to be on CRAN first, which I submitted some hours ago...

**Comment by IndrajeetPatil** [comment] 2021-09-02 06:49
Still stuck in [pretest](https://lockedata.github.io/cransays/articles/dashboard.html):

![image](https://user-images.githubusercontent.com/11330453/131795964-c4fe81c8-3036-463b-b758-10b1242d4319.png)

The `insight` update seems to have made it to CRAN though.

**Comment by DominiqueMakowski** [comment] 2021-09-02 07:51
submitted

**Comment by bwiernik** [comment] 2021-09-02 17:09
datawizard in PreCheck now! ![image](https://user-images.githubusercontent.com/4773225/131887408-2c3e2c0c-c734-4bc1-bb7e-0f73b3452cae.png)

**Comment by DominiqueMakowski** [comment] 2021-09-03 00:12
Dear maintainer,

thanks, package bayestestR_0.11.0.tar.gz is on its way to CRAN.

![](https://media.giphy.com/media/JMV7IKoqzxlrW/giphy.gif?cid=ecf05e47wazedkc2p0zbk48ltrabewjxm7j78a1v1thc1gm3&rid=giphy.gif&ct=g)

**Closed** 2021-09-03 00:12 UTC
Labels: high priority :runner:
